* puremacs

Dotfiles for learning emacs without git

[[puremacs][file:http://i.imgur.com/4LWWsy5.jpg]]

** Currently Using

*** Miscellaneous Settings
    No menus, start screen, tool bars or menu bar.
    Auto matching and highlighting parens.
    Spaces instead of tabs.

*** use-package
    For package management and auto installation

*** doom-themes
    For an atom one like theme for emacs

*** ido
    For nicer completion and option selection

    [[ido][file:http://i.imgur.com/VBHYTj8.jpg]]

*** smex
    For ido in the `M-x` buffer

    [[smex][file:http://i.imgur.com/iw3gUPU.jpg]]

*** ido-complete-space-or-hyphen
    Inserts a hyphen/space if any of the possible completion candidates have a hyphen/space when autocompleting using ido/smex.

*** expand-region
    Intelligently increases selected region using code syntax as guides.

    [[expandregion][file:http://i.imgur.com/ieX2sDR.jpg]]

*** magit
    Git percelen inside of emacs

*** org-bullets
    Shows nice bullets in org mode instead of just asterisks
    
    [[org-bullets][file:http://i.imgur.com/8w3Qwgd.jpg]]
